image: node

stages:
  - test
  - jsdoc
  - deploy

test:
  stage: test
  script:
    - npm install
    - npm run test
  artifacts:
    paths:
      - coverage

jsdoc:
  stage: jsdoc
  script:
    - npm install
    - npm run doc
  artifacts:
    paths:
      - docs

pages:
  stage: deploy
  script:
    - mkdir public/coverage
    - cd coverage
    - mv * ../public/coverage
  artifacts:
    paths:
      - public
