image: node

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - npm install
    - npm run test
  artifacts:
    paths:
      - coverage

pages:
  stage: deploy
  script:
    - mkdir public/coverage
    - cd coverage
    - mv * public/coverage/
  artifacts:
    paths:
      - public
